Rook methods tests
Skotee/CodersCamp2020.Project.TypeScript.Chess.AKTeam pull request #29
Opened 2021-02-03 19:05 UTC by Skotee

2021-02-03 19:32 UTC, Chlip requested changes
zmienic niektore nazwy zmiennych

2021-02-03 19:32 UTC, Chlip commented on test/Board/RookMove.test.ts
> +    const knight = new Rook(PieceColor.White, PieceType.Rook, new Square(0, 6));
knight != rook, zmienic

2021-02-03 19:32 UTC, Chlip commented on test/Board/RookMove.test.ts
> +    const knight = new Rook(PieceColor.White, PieceType.Rook, new Square(7, 1));
knight != rook

2021-02-03 19:38 UTC, jkilar approved these changes
wygląda dobrze

2021-02-03 20:31 UTC, Chlip requested changes

2021-02-03 20:31 UTC, Chlip commented on test/Board/RookMove.test.ts
> +    const game = new Game(undefined, undefined, undefined, undefined, undefined, board);
musimy wiedziec czy jest ruch wiec 2 argument w Game powinien byc PieceColor

2021-02-04 18:13 UTC, Chlip approved these changes

2021-02-04 18:14 UTC, merged