End game rules test
Skotee/CodersCamp2020.Project.TypeScript.Chess.AKTeam pull request #40
Opened 2021-02-06 14:21 UTC by jkilar

2021-02-06 21:02 UTC, Chlip requested changes

2021-02-06 21:02 UTC, Chlip commented on test/Game/EndGameRules.test.ts
> +
do wyrzuecnia

2021-02-06 21:02 UTC, Chlip commented on test/Game/EndGameRules.test.ts
> +        let newMove12 = new Move(new Square(5, 1), new Square(4, 1), wBishop, null);
do wyrzucenia

2021-02-07 13:51 UTC, Chlip approved these changes

2021-02-07 21:13 UTC, Skotee commented on test/Game/EndGameRules.test.ts
> +        const bRook = new Rook(PieceColor.Black, PieceType.Rook, new Square(3, 6));
```suggestion
        const blackRook = new Rook(PieceColor.Black, PieceType.Rook, new Square(3, 6));
```

2021-02-07 21:15 UTC, Skotee approved these changes

2021-02-07 21:15 UTC, merged